Repository tafcoder/sleek-dashboard, pull requests merged in 2018-09, with the labels that each got.

#12 Documentation: add contributing and update readme
  CONTRIBUTING.md
  README.md
Labels: enhancement

#21 Fix some responsive issue with table and create data-attribute way for content scrolling
  src/_inc/analytics-device.htm
  src/_inc/area-chart.htm
  src/_inc/new-customers.htm
  src/_inc/notification.htm
  src/_inc/page-view.htm
  src/_inc/profile-tiny.htm
  src/_inc/recent-order-table.htm
  src/_inc/sales-overview-graph.htm
  src/_inc/to-do-list.htm
  src/_inc/top-products.htm
  src/_inc/top-sold-table.htm
  src/assets/js/custom.js
  src/assets/scss/_card.scss
  src/assets/scss/_tables.scss
Labels: bug

#39 Fix layout
  src/_inc/footer.htm
  src/_inc/header.htm
  src/_inc/sidebar-with-footer.htm
  src/_inc/sidebar.htm
  src/_inc/top-bar.htm
  src/alert.html
  src/analytics.html
  src/assets/js/sleek.js
  src/assets/scss/_grid.scss
  src/assets/scss/_navbar.scss
  src/assets/scss/_sidebar.scss
  src/badges.html
  src/bredcrumb.html
  src/button-group.html
  src/button-loading.html
  src/button-social.html
  src/buttons.html
  src/calendar.html
  src/card.html
  src/carousel.html
  src/chart-widgets.html
  src/charts-chartjs.html
  src/collapse.html
  src/custom-icons.html
  src/dropdowns.html
  src/error.html
  src/flag-icons.html
  src/fontawesome-icons.html
  src/form-advance.html
  src/form-basic-input.html
  src/form-checkbox-radio.html
  src/form-input-group.html
  src/form-validation.html
  src/general-widgets.html
  src/google-map.html
  src/header-dark.html
  src/header-fixed.html
  src/header-light.html
  src/header-static.html
  src/index.html
  src/invoice.html
  src/list-group.html
  src/modal.html
  src/pagination.html
  src/popover-tooltip.html
  src/profile.html
  src/progressbar.html
  src/sidebar-minimized.html
  src/sidebar-offcanvas.html
  src/sidebar-open.html
  src/sidebar-with-footer.html
  src/sidebar-without-footer.html
  src/signin.html
  src/signup.html
  src/spinners.html
  src/switchers.html
  src/tables.html
  src/tabs.html
  src/vector-map.html
Labels: bug

#41 Fix sidebar menu 'active link' problem and some other issues
  src/_inc/sidebar-with-footer.htm
  src/_inc/sidebar.htm
  src/assets/js/sleek.js
  src/assets/scss/_sidebar.scss
  src/index.html
Labels: bug, enhancement
